apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: "Terraform Template"
  title: "Template for AWS S3"
  description: Create Your S3 Resource Here
  tags:
    - s3
spec:
  owner: my-awesome-team
  type: service

  parameters:
    - title: Enter the Resource Identification Name
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name for the tf module
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
