apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-template
  title: Terraform Tempalte for AWS S3
  description: My Example discription here
  links:
    - url: https://github.com/mythun-git/software-templates/edit/main/scaffolder-templates/backstage/terraform.yaml
      title: Github
      icon: github 
spec:
  owner: mythun-git
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Enter the resource name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the resource
          ui:autofocus: true
          ui:options:
            rows: 5
            
    - title: Fill the S3 Bucket Details
      required:
        - bucketName
      properties:
        bucketName:
          title: Bucket Name
          type: string
          description: Enter the Name of the Bucket
          ui:autofocus: true
          ui:options:
            rows: 5
        bucketRegion:
          title: Bucket Region
          type: string
          description: Enter the Region for the bucket (Refer AWS Regions)
          ui:autofocus: true
          ui:options:
            rows: 5
    
            
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
